# docker-compose up --build
# docker-compose build --no-cache
version: '3.8'
services:
  web:
    container_name: poc.admin.react
    build: .
    ports:
      - '80:3000'
    volumes:
      - .:/app
      - /app/node_modules
